index.html
기존에 연사 추천 양식으로 이어져있던 발표자 신청 링크를 발표자 신청 양식으로 링크했습니다!
=> 발표자 신청 링크 수정

index.html, sponsorship.html
- 메인페이지 footer 페이스북 연결 링크에 `https://`가 빠져 연결이 안되고 있어 `https://`를 추가했습니다.
- 스폰서등급별 구좌수가 잘못 기재된거 같아 아래와 같이 수정했습니다. 맞게 수정한것인지 확인 부탁드립니다. ->  @jungchulha 
**as -is**
등급 |다이아몬드|플레티넘|골드|실버
----|------|------|------|----
구좌수|1|3|5|제한없음
**to-be**
등급|다이아몬드|플레티넘|골드|실버
---|----|------|------|----
구좌수|제한없음|5|3|1
=> 이슈번호가 없지만...날려봅니다.

index.html
=> organizer 를 추가했습니다

index.html
=> 사용하지 않는 링크 지움 &페이스북 데놀자로 가는 버튼 생성

index.html
랜덤한 시간에 얼리버드 참가신청을 close하기위한 준비입니다.~~^^
=> 얼리버드 참가신청 Close

index.html
=> add presenter : 백정상

index.html
=> 참가신청 Close

index.html
=> 2차티켓팅 close

data-book-recommendation-2017.html, organization-chart.html, program-2017.html, sponsorship.html
프로그램, 추천도서, 조직도, 상호후원에 메타태그를 추가했습니다.
=> 프로그램, 추천도서, 조직도, 상호후원에 메타태그를 추가했습니다.

sponsorship.html
- 기타 후원 부분에서 두레이 제외 
- 브론즈 영역에 추가
=> 두레이 브론즈 영역 추가

program-list-2017.html
금상은/이종필의 "음악 데이터 수집부터 웹 어플리케이션까지"에 대한 업데이트입니다.
=> Update program-list-2017.html [금상은/이종필]

program-list-2017.html
=> 김석준 상세소개글 수정입니다!

program-2017.html
프로그램 페이지의 데이터 이야기 아래에 나타나는 임도형 이름을 제거하였습니다.
=> 중복되어 오류 발생하는 코드 제거

assets/css/main.css, program-2017.html
링크가 있는 프로그램에 한해 발표자료 아이콘과 링크를 추가했습니다.
없는 자료가 많아 링크를 수집하시면 알려주세요.
=> 프로그램에 발표자료 추가

2017-datayanolja/README.md, 2017-datayanolja/README.txt
=> changed README.txt to README.md

index.html, ticket.html
=> 2018데놀 1차 참가신청

index.html, ticket.html
=> 마지막 티켓팅 오픈

program.html, speakers/ungikim.html, speakers_main.html
안녕하세요.  김운기입니다.

발표자로써 정보를 등록합니다.
=> 김운기 발표자의 정보 등록

speakers/songsukree.html
=> Add songsukree for speaker

speakers/kwangchun2.html
=> 소프트웨어 카펜트리 시즌2 발표자료

program.html
=> 김현중님 링크 추가
